### ISSUE TITLE
Description of this repo needs update

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes-sigs/prow#108]
Description of this repo needs update, since we have Prow codes as well in this repo.

[As-is]
> Statically generated docs for Prow (the tool that currently resides in kubernetes/test-infra). For historical reasons Prow lives in kubernetes/test-infra along with other things, but this repo is all about Prow.

![image](https://github.com/kubernetes-sigs/prow/assets/46767780/2a07db1a-88fe-4cbc-9e28-9d83b0f4dcc5)

**Comment by petr-muller** [comment]
I changed the GH description to:

>  Prow is a Kubernetes based CI/CD system developed to serve the Kubernetes community. This repository contains Prow source code and Hugo sources for Prow documentation site.

**Comment by jihoon-seo** [comment]
@petr-muller Thank you!
