### ISSUE TITLE
Broken link in branch protection

### ISSUE THREAD

**Issue by clobrano** [kubernetes-sigs/prow#109]
Link to [`branch_protection.go`](https://github.com/kubernetes/test-infra/tree/master/prow/config/branch_protection.go) is broken in https://docs.prow.k8s.io/docs/components/optional/branchprotector/

**Comment by jihoon-seo** [comment]
Hello @clobrano,
there exists a PR that I have opened: #103
(Updating line: https://github.com/kubernetes-sigs/prow/pull/103/files#diff-b0fd935141fbcc52c0b9c1aabc15bccdc1288635e695a46c28530fa73226dbd7R207)

Once the PR gets merged, I presume that this issue will be resolved. 😊

/assign

**Comment by clobrano** [comment]
@jihoon-seo awesome! Thanks!
