### ISSUE TITLE
branchprotector does not honor CTRL-C

### ISSUE THREAD

**Issue by tuminoid** [kubernetes-sigs/prow#118]
Shortly: branchprotector does not honor CTRL-C and if killed, may leave threads running on the background.

I did a dry-run as [suggested by the docs](https://docs.prow.k8s.io/docs/components/optional/branchprotector/#deploy-cronjob-to-production) and wanted to cancel it as it took so long to run. 

Issue:
1. it doesn't honor CTRL-C, it does nothing
2. if suspended by CTRL-Z, and killed, it leaves worker threads behind, which keep running and spamming until separately killed

How to reproduce:
```
go run ./prow/cmd/branchprotector \
  --config-path=/path/to/config.yaml \
  --github-token-path=/path/to/my-github-token
```
Our [prow config](https://github.com/metal3-io/project-infra/blob/main/prow/manifests/overlays/metal3/config.yaml) for reference.

**Comment by jihoon-seo** [comment]
We might update branchprotector code to handle OS signals.

Ref:
- [Handle CTRL-C in Golang](https://gist.github.com/jnovack/297cee036f3e5a430aa9444c0ae1b06d)
- [Is it possible to capture a Ctrl+C signal (SIGINT) and run a cleanup function, in a "defer" fashion?](https://stackoverflow.com/questions/11268943/is-it-possible-to-capture-a-ctrlc-signal-sigint-and-run-a-cleanup-function-i)
- [Exit Go program on Ctrl+C](https://stackoverflow.com/questions/24608210/exit-go-program-on-ctrlc)

**Comment by tuminoid** [comment]
/assign

Well I need it fixed so I can dry-run branchprotector vs our config where it acts funny, so I'll send a PR soon.
