### ISSUE TITLE
Tide blocks PRs which have checks with "skipped" status

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/prow#130]
Since a few days (I think since the weekend) tide is not merging PRs with skipped actions anymore.

It reports: Pending — Not mergeable. Job Approve ok-to-test has not succeeded.

For full context, see: https://kubernetes.slack.com/archives/C09QZ4DQB/p1713803378307299

It looks like GitHub changed the "check-runs" API to additionally return a "skipped" status which is not handled in https://github.com/kubernetes-sigs/prow/blob/a25fe4dde1396f35028dc56f0de2223765683399/pkg/tide/tide.go#L2133-L2139

Some referenced:
* Our action: https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/pr-gh-workflow-approve.yaml
* Some blocked PRs:
  * https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2930
  * https://github.com/kubernetes-sigs/cluster-api/pull/10477

<img width="1137" alt="image" src="https://github.com/kubernetes-sigs/prow/assets/4662360/b0e6400a-227a-4438-b85b-11203b13fb44">

This will affect a few more repositories as just this action alone was copy&pasted across a few repos: ~ https://cs.k8s.io/?q=%27ok-to-test%27&i=nope&files=&excludeFiles=&repos=

**Comment by tuminoid** [comment]
+1. We also hit same in Metal3 today. Skipped optional action was blocking tide from merging. Worked around it by editing PR title which causes actions to run again, and then tide agreed to merge.

**Comment by cardil** [comment]
+1. This affects a lot of Knative repos. For example: https://github.com/knative/serving/pull/15147

**Comment by dprotaso** [comment]
Oddly the Check run API isn't returning skipped jobs ATM

```sh
gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/knative/serving/commits/acdcf4fd9bad1fce9f17a29f3638ede1833cf8c9/check-runs | jq '.check_runs | .[] | .name'
```

**Comment by JohnNiang** [comment]
I faced the same problem yesterday.

<img width="832" alt="image" src="https://github.com/kubernetes-sigs/prow/assets/16865714/6ede3a58-dd05-418a-a2a2-9a6aae06ea00">

```json
{
      "id": 24134812784,
      "name": "github-release",
      "node_id": "CR_kwDOB4VVe88AAAAFnowEcA",
      "head_sha": "ff334baa39e8d8ff74886c5d9b6de342f1f6ae5b",
      "external_id": "4ff2e047-c2ab-5477-8844-6e71b9d83ccc",
      "url": "https://api.github.com/repos/halo-dev/halo/check-runs/24134812784",
      "html_url": "https://github.com/halo-dev/halo/actions/runs/8751217578/job/24134812784",
      "details_url": "https://github.com/halo-dev/halo/actions/runs/8751217578/job/24134812784",
      "status": "completed",
      "conclusion": "skipped",
      "started_at": "2024-04-23T04:23:25Z",
      "completed_at": "2024-04-23T04:23:25Z",
      "output": {
        "title": null,
        "summary": null,
        "text": null,
        "annotations_count": 0,
        "annotations_url": "https://api.github.com/repos/halo-dev/halo/check-runs/24134812784/annotations"
       }
}
```

**Comment by saschagrunert** [comment]
@sbueringer are you already working on a fix for this?

**Comment by sbueringer** [comment]
@saschagrunert No, mostly because I'm not familiar with the code base and I don't know if it is more than just adjusting that one single if

**Comment by saschagrunert** [comment]
Working towards a fix in https://github.com/kubernetes-sigs/prow/pull/131

**Comment by saschagrunert** [comment]
It works, PR's like https://github.com/kubernetes-sigs/security-profiles-operator/pull/2225 merge again. :)

**Comment by sbueringer** [comment]
Thank you very much!
