### ISSUE TITLE
[Feature]: [assign plugin] Support GitHub Organization Teams as targets for assign/cc commands

### ISSUE THREAD

**Issue by bells17** [kubernetes-sigs/prow#145]
Would it be possible to support GitHub Organization Teams as targets for the assign/cc commands?

Currently, I am working on the contextual logging feature, which follows a specific review process for PRs:

```
/cc [@]kubernetes/wg-structured-logging-reviews
```

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#what-to-include-in-the-pull-request

However, prow does not support `/cc <teams>`, resulting in an error.

In most cases, the reviewers selected by the blunderbuss plugin based on the OWNERS file are sufficient. However, for PRs like the one below, the hack directory may not necessarily include members of [@]kubernetes/wg-structured-logging-reviews.
https://github.com/kubernetes/kubernetes/pull/124722

If `/cc <teams>` were supported, I think it would simplify the review request process for above case.
(This is because there would be no need to send review requests to specific individuals within the team.)

**Implementation proposal:**
- Allow `/cc <teams>` and `/assign <teams>` commands to randomly select one member from the specified team as a reviewer or assignee. We could discuss whether adjusting the number of selections might be necessary.
- [Implement this using the `layeredsets.PopRandom()` function, already utilized in the blunderbuss plugin, for random selection](https://github.com/kubernetes-sigs/prow/blob/c5e374dc7eb1aa4283a37d4a8f68bd67f52e22ad/pkg/plugins/blunderbuss/blunderbuss.go#L328-L359).
- Ensure that the GitHub teams used for PRs within the Kubernetes org are limited to those within the Kubernetes org, maintaining organizational alignment.

I would appreciate your thoughts on this issue.

/kind feature

**Comment by Okabe-Junya** [comment]
I also want this feature!!

> Allow /cc <teams> and /assign <teams> commands to randomly select one member from the specified team as a reviewer or assignee. We could discuss whether adjusting the number of selections might be necessary.

I think this idea is great. Another approach is to assign the entire team as reviewers. (This would result in a bit more noise in notifications, but GitHub [support this feature](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team))

In any case, I am looking forward to this feature :)

**Comment by Okabe-Junya** [comment]
Can I work on this issue? let me assign

/assign

**Comment by smg247** [comment]
I see that this feature was attempted and then reverted, but I am skeptical that a change here is necessary at all. I have always been able to use `cc` with a github team. For example, I use `/cc @openshift/test-platform` often in our installation, and it ccs the team itself rather than the individual members. This had stopped working for awhile, and I see now it was due to the bug described in https://github.com/kubernetes-sigs/prow/issues/204.

**Comment by smg247** [comment]
If this feature is attempted again, it should at least be behind a configuration so that installations that would like to retain the existing behavior are able to do so.

**Comment by Okabe-Junya** [comment]
Thank you for your comment, @smg247

Since this issue is already closed, please comment on issue #204 as you mentioned, thanks
