### ISSUE TITLE
Prow issue:Re: [kubernetes/kubernetes] Regarding the issue of certificate expiration when accessing links with Https in kubernetes through pod access (Issue #125130)

### ISSUE THREAD

**Issue by 1569099266** [kubernetes-sigs/prow#162]
I curl any link with HTTPS in the ingress nginx controller pod in Kubernetes, and the HTTPS certificate will expire at the same time. However, I have no problem curling on the node, and I have no problem starting an nginx container curl using Docker

**Comment by 1569099266** [comment]
Screenshot of testing on a physical machine
![image](https://github.com/kubernetes-sigs/prow/assets/46311200/43605ddc-70f0-4845-9131-8337e5e9f63f)

Screenshot of testing in Pod, regardless of the website used, the test result shows that the HTTPS certificate has expired
![Uploading 1716732286467.png…]()

**Comment by BenTheElder** [comment]
This has nothing to do with prow.
/close
