### ISSUE TITLE
Prow web UI exposes private repositories

### ISSUE THREAD

**Issue by ivanvc** [kubernetes-sigs/prow#201]
The [plugin catalog](https://prow.k8s.io/plugins) and the [command help](https://prow.k8s.io/command-help) pages expose private repositories in the repository dropdown. For example, both show the repository etcd-io/etcd-ghsa-j8g6-82f3-cvhp, which is private.

I tried tracing the issue, and it seems to come from `(client) GetRepos(...)`, as it gets all the repositories accessible to the user/organization without filtering (however, I may be wrong that this is the root cause):

https://github.com/kubernetes-sigs/prow/blob/79d27b6e3be35974fbe103d3f574d70dfea6f03c/pkg/github/client.go#L2529-L2560

**Comment by smg247** [comment]
This is obviously not expected behavior, but this doesn't seem harmful to me. You can see the repositories in the dropdown, but there is no data there when selected. Essentially, we are leaking names of private repositories. Is there a reason you can think of where this is a serious issue?

**Comment by BenTheElder** [comment]
FWIW, if this is considered a problem, I'd _highly_ recommend using a distinct instance.

prow.k8s.io _used_ to have private repositories for some sensitive embargoed security-patch related work, but that's not the approach now, and the Kubernetes project is primarily focused on open repos.

It's super likely that there will be other gaps and I would encourage using an isolated deployment for anything so sensitive that the names of the repos are considered an info leak.

**Comment by ivanvc** [comment]
I don't have a local Prow deployment. However, I noticed this information leak while checking Prow's Web UI. I don't know if other Kubernetes organizations make use of private repositories. I noticed etcd's because I'm a contributor.

Feel free to close if you feel this is irrelevant or the risk is minor :)

**Comment by BenTheElder** [comment]
We should probably consider this a bug anyhow, I just didn't want anyone getting the wrong idea about how secure this is.

That includes etcd, we should discuss privately in slack with the other K8s Infra / Testing leads about the requirements for etcd and private repos.
