### ISSUE TITLE
[BUG] CC multiple people does not work anymore

### ISSUE THREAD

**Issue by gregpavl** [kubernetes-sigs/prow#204]
**What happened**:

We upgraded the prow components from `v20231227` to `v20240515`. 

example: 

```
-        image: gcr.io/k8s-prow/prow-controller-manager:v20231227-1f5d684b52
+        image: gcr.io/k8s-prow/prow-controller-manager:v20240515-dd5d0eeaa
```

Before the upgrade, 
the command `/cc @person_1 @person_2 @person_3 @person_4` was CC the GH usernames correctly (all at once) in the PRs. 

After the upgrade, 
the CC functionality seems broken. 
If you try to CC multiple people, the bot will catch only the first CCed user.

**What you expected to happen**:

to continue CC multiple people with the same command inline at once.

**How to reproduce it (as minimally and precisely as possible)**:

try to CC people on the same line. `/cc @person_1 @person_2 @person_3 @person_4` 
you can even try to `/cc @person_X` multiple people in the same comment. It has the same behavior.

Right now, you need to do CC people in separate comments. 

Eg. 
Comment 1: 
`/cc @person_1` 
Comment 2: 
`/cc @person_2` 
Comment 3: 
`/cc @person_3` 
Comment 4: 
`/cc @person_4` 

**Please provide links to example occurrences, if any**:

n/a

**Anything else we need to know?**:

- k8s cluster: 1.28.10-do.0 (v. 1.28.10 - managed by DO)
- github org | free

---

original ref: https://github.com/kubernetes/test-infra/issues/32905

**Comment by droslean** [comment]
My first thought is maybe https://github.com/kubernetes-sigs/prow/pull/164/ is related. @Okabe-Junya Any ideas?

**Comment by Okabe-Junya** [comment]
Upon checking the git history, it seems that the only change to the assign plugin after the migration to k-sigs/prow was my PR(#164). 

I apologize if this caused any inconvenience. I have created a PR to revert #164, which might serve as a useful workaround for now.

**Comment by Okabe-Junya** [comment]
What I don't understand is that while my PR was merged on **May 28**, the tag where the bug happened is `v20240515`. (Is this tag based on the date the image was built?)

Moreover, my PR only changed the behavior for teams, so it shouldn't have affected the `/cc Alice Bob ...` format command at all. All elements should result in the `isTeamLogin` function returning false, meaning that simply `users[login] = add` would be executed.

https://github.com/kubernetes-sigs/prow/blob/79d27b6e3be35974fbe103d3f574d70dfea6f03c/pkg/plugins/assign/assign.go#L137-L148

**Comment by Okabe-Junya** [comment]
I am not sure if this will directly resolve the bug, but I did find one bug. I misunderstood the signature of the [`ListTeamMembersBySlug` function](https://github.com/kubernetes-sigs/prow/blob/79d27b6e3be35974fbe103d3f574d70dfea6f03c/pkg/github/client.go#L3758-L3786) and made an incorrect call. I have created a PR to fix this - #206

**Comment by Okabe-Junya** [comment]
@droslean 

ref. https://github.com/kubernetes-sigs/prow/issues/204#issuecomment-2209361096

I want to check the image tag. It looks like the tag is from before my PR was merged. Do you have any idea what could be the cause?

> What I don't understand is that while my PR was merged on **May 28**, the tag where the bug happened is `v20240515`. (Is this tag based on the date the image was built?)

**Comment by Okabe-Junya** [comment]
@gregpavl 

I created and merged a [revert PR](https://github.com/kubernetes-sigs/prow/pull/205) - this issue might be resolved in the latest Prow image.

If possible, please let me know if this bug is resolved, thanks!

**Comment by Okabe-Junya** [comment]
ref. https://github.com/kubernetes-sigs/prow/issues/145#issuecomment-2239909009

> I see that this feature was attempted and then reverted, but I am skeptical that a change here is necessary at all. I have always been able to use `cc` with a github team. For example, I use `/cc @openshift/test-platform` often in our installation, and it ccs the team itself rather than the individual members. This had stopped working for awhile, and I see now it was due to the bug described in #204.

I think the reason why issue #204 was created is that the command in the format `cc @org-name/team-name` could not be executed. Even after checking the source code, it appears that mentions in the format containing "/" are not handled.

https://github.com/kubernetes-sigs/prow/blob/e49eac6829a97ec9c4a6e9509e5588b87aaeada0/pkg/plugins/assign/assign.go#L122-L131

Meaning, isn't it just using GitHub's feature to mention, rather than a command from prow?

**Comment by Okabe-Junya** [comment]
I don't think this discussion has been resolved yet, though...

https://github.com/kubernetes-sigs/prow/issues/204#issuecomment-2241171624
