### ISSUE TITLE
Git providers other than GitHub

### ISSUE THREAD

**Issue by wbrefvem** [kubernetes-sigs/prow#236]
Carrying this over from https://github.com/kubernetes/test-infra/issues/10146 . 

@BenTheElder You mentioned on the other thread that there's been no bandwidth for this. I haven't looked at prow in quite awhile, but I'd love to jump back in if there's an appetite for it.

**Comment by BenTheElder** [comment]
Prow is probably at the lowest point ever in terms of maintainer bandwidth from what I can tell, but it's still essential to the project, making sweeping changes difficult to enable.

I'm not working on it directly currently, just the SIG overall and getting prow.k8s.io fully running under SIG K8s Infra (done for the jobs now but not the services, that's next week)
