### ISSUE TITLE
As an unprivileged user, I can write to prow on the server side.

### ISSUE THREAD

**Issue by jgao1025** [kubernetes-sigs/prow#246]
Not sure if this is an expected behaviour, but it looks werid to me?

So I opened this [CI build history](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-gateway-api-verify), and click any error builds. The build log can highlight error lines in color, which is helpful. However, once I clicked the 'Analyzed' button, everything changed, and I can't find a way to revert it. Additionally, this seems to affect the server side as well.

**Comment by BenTheElder** [comment]
That's just running an analysis tool, which we're no longer deploying. It was called halogen. https://github.com/kubernetes/test-infra/pull/33353

/close
