### ISSUE TITLE
FontAwesome icons are not displayed

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes-sigs/prow#27]
[env]
- Windows 10 64-bit + Google Chrome 107.0.5304.107 64-bit // Microsoft Edge 107.0.1418.56 64-bit
- Ubuntu 18.04 desktop 64-bit + Firefox 107.0 64-bit // Google Chrome 96.0.4664.45 64-bit

![image](https://user-images.githubusercontent.com/46767780/203722599-8a8004eb-0ef8-42a9-8006-529e4ffa7b7f.png)
![image](https://user-images.githubusercontent.com/46767780/203722688-7d0eb181-fe08-454c-99ae-7825fd5bb0cb.png)

---

On the other hand, those are displayed correctly in [Netlify preview](https://deploy-preview-26--k8s-prow.netlify.app/) and local preview

![image](https://user-images.githubusercontent.com/46767780/203723510-da2bb2e6-e654-4380-82e6-8f3c58deb92e.png)
![image](https://user-images.githubusercontent.com/46767780/203723562-2327a6c5-02fe-40d6-89a7-bb108cc8aa87.png)

---

My guesses are:
- On Netlify production build session, files under `public/webfonts/` are not located correctly.
  - The [home page](https://docs.prow.k8s.io/) imports the [CSS file](https://docs.prow.k8s.io/scss/main.min.0ad905b28f9554d460e15a941b109647451c54c6486012593e2362675c7d70c9.css) that Hugo generated.
  - The CSS file tries to import webfont files, but if I try to reach the webfont URL, I see 404 Not Found.
    - https://docs.prow.k8s.io/webfonts/fa-solid-900.eot
    - https://docs.prow.k8s.io/webfonts/fa-solid-900.woff2
    - https://docs.prow.k8s.io/webfonts/fa-solid-900.svg
    - ...
    - On the other hand, I can reach one of the webfont file type (`woff2`) for the Netlify preview case.
    - https://deploy-preview-26--k8s-prow.netlify.app/webfonts/fa-solid-900.woff2
- [This site imports Docsy](https://github.com/kubernetes-sigs/prow/blob/main/.gitmodules), and in turn Docsy imports FontAwesome (as of Docsy [v0.3.0](https://github.com/google/docsy/blob/v0.3.0/.gitmodules) // [latest](https://github.com/google/docsy/blob/main/package.json)).
  - We might dig more on this importing chain and production-file generation processes.
  - Or, we might use the CDN-version of FontAwesome webfont instead.

**Comment by listx** [comment]
This appears to have been fixed.

/close
