### ISSUE TITLE
Bump Hugo & other dependencies

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes-sigs/prow#28]
Currently this repo is [configured](https://github.com/kubernetes-sigs/prow/blob/main/netlify.toml) to use Hugo 0.91.2 for Netlify builds.

If possible, we might bump Hugo to newer version.

Ref: https://github.com/kubernetes/website/pull/34356

And other dependencies are:
- [Docsy](https://github.com/kubernetes-sigs/prow/blob/main/.gitmodules)
- [node_modules / autoprefixer, postcss, postcss-cli](https://github.com/kubernetes-sigs/prow/blob/main/site/package.json)

**Comment by listx** [comment]
I've updated some dependencies as part of #35 (notably Docsy to 0.6.0).

Not sure if we need to bump Hugo itself. WDYT @jihoon-seo ?

**Comment by jihoon-seo** [comment]
Like all other dependencies, upgrading Hugo is not a mandatory thing, but seems to be a good thing to do.. 🙂

> Notable new features of Hugo v0.101.0:
> 
> * indentation fixes to shortcode blocks
> * [`resources.Copy`](https://gohugo.io/hugo-pipes/introduction/#copy-a-resource) function
> * improved error handling

**Comment by listx** [comment]
I just noticed that Mermaidjs diagrams are not working locally. I think updating Hugo might help here.

**Comment by jihoon-seo** [comment]
> The only downside here is that there could be a mismatch between this container and what Netlify uses. I'm not sure what the best practice is here.

k/w case:
- Hugo version for Netlify (preview & prod) is configured in [`netlify.toml`](https://github.com/kubernetes/website/blob/main/netlify.toml), which this repo also has.
- In [`Makefile`](https://github.com/kubernetes/website/blob/main/Makefile), that Hugo version is extracted from `netlify.toml` with `grep`
- In some Makefile rules that run container, use the extracted Hugo version as a part of container image tag, which in turn is pulled and run.

About Mermaid.js,
there had been issues that Mermaid diagrams were not displayed correctly,
and AFAIK this has been fixed by some PR.
Please see https://github.com/kubernetes/website/pull/34794, and some other issues & PRs if needed.

**Comment by listx** [comment]
We should probably do something similar to what k/w does wrt grepping the Hugo version so that the container closely matches whatever Netlify uses.

WRT https://github.com/kubernetes/website/pull/34794 I see that they just check in the actual MermaidJS source code directly into a static asset folder. I'm not sure about this (although I don't have strong opinions either way).
