### ISSUE TITLE
[Help Wanted] Is there anyway to configure prow trigger plugin, if there is ok-to-test label, it can trigger github workflows automatically?

### ISSUE THREAD

**Issue by JesseStutler** [kubernetes-sigs/prow#284]
Hi, I'm a contributor from the volcano community. In our community, when a contributor submits a pull request (PR) for the first time, the owner must manually click on the CI to trigger it. Currently, this is a bit troublesome because the owner doesn't have much time to manage these tasks. Instead, we have a volcano-bot using prow. Prow should be able to automatically trigger CI if there is an `ok-to-test` label. However, we run e2e tests using GitHub workflows. Is there any way to configure the prow trigger plugin so that if there is an `ok-to-test` label, it can automatically trigger GitHub workflows? Thanks!

**Comment by petr-muller** [comment]
Hi! Looks like you discovered the related issue #194 so closing this one
