### ISSUE TITLE
[Question] Does the Prow job schedule VM as  executable unit?

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes-sigs/prow#315]
Hi team, 
We have some workloads that have to run on a VM, not a Pod. IMO, the prow job uses a pod as an executable unit, right? So, can we configure VM as an executable unit to run something? Thanks! If yes, how to do it? If not, do we have a plan for it?

**Comment by petr-muller** [comment]
I'm not aware of any such capability, and there are no plan for it. Given the low maintenance capacity we have right now, I don't think we would even have capacity to work on it or even review and maintain an external contribution). 

The typical approach for this kind of thing would be to have a "driver" tool that runs as a Kube workload in a pod, and handles the provisioning and teardown of the external resource such as VM.

I know you come from OpenShift so I'm not sure I understand where's the ask coming from - IIRC OpenShift does not use bare Prow jobs, it uses the `ci-operator` (it's basically a "driver" tool like I describe above), and it should not be hard to write `ci-operator` steps that provision a VM and run a test workload on it.

**Comment by BenTheElder** [comment]
In the Kubernetes project we rent external resources from https://github.com/kubernetes-sigs/boskos

**Comment by jianzhangbjz** [comment]
Many thanks both! we will have a try!
