### ISSUE TITLE
trigger: Improve experience of guided comment

### ISSUE THREAD

**Issue by wuhuizuo** [kubernetes-sigs/prow#321]
https://github.com/kubernetes-sigs/prow/blob/b21d1cf485474d6da2623ccc40849e2c8b24b2e5/pkg/pjutil/help.go#L75

Maybe we can make the line copied able in GitHub PR comment.

Many people are used to copying the instructions given in the comments and then creating new trigger comments, but it is easy to copy the leading blank characters, which will cause the `trigger` plugin to reject such instructions. By introducing the click-copy feature, this situation will be effectively avoided, and it will be more convenient to use.

In terms of the solution, this does not need to rely on any other third-party functions. GitHub markdown itself supports this capability. We only need to fine-tune the markdown format to do it.

The following is a comparison of the effects.

Before:
```md
@wuhuizuo: The specified target(s) for `/test` were not found. The following commands are available to trigger required jobs:

* `/test pull-unit-test`
```
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/d9c36627-2b49-483d-bbe6-32261e261509">

After:
```md
@wuhuizuo: The specified target(s) for `/test` were not found. The following commands are available to trigger required jobs:

*     /test pull-unit-test
```
![image](https://github.com/user-attachments/assets/383eade6-1c1b-4c02-8aa5-0a3ecdcbf1f3)

The different between the two markdown contents:
```diff
3c3
< * `/test pull-unit-test`
---
> *     /test pull-unit-test
```

**Comment by petr-muller** [comment]
I kinda like this - it looks better especially with short lists. I am a bit concerned about how much space this takes when you have 10+ jobs configured, which is not uncommon.

If we do this then we no longer need to use bullet points though, and then we can easily use the triple ticks instead of the four-blank indent, like this:

    ```
    /test one
    ```
    ```
    /test two
    ```

which gets rendered into:


```
/test one
```
```
/test two
```

**Comment by petr-muller** [comment]
I can see us using this markup even in other places that suggest commands

**Comment by wuhuizuo** [comment]
> I can see us using this markup even in other places that suggest commands

Yes, it's better to replace the entire thing at once.

**Comment by petr-muller** [comment]
> Yes, it's better to replace the entire thing at once.

That's not what I wanted to suggest. I simply like the proposal. I'm happy to accept multiple smaller PRs, not necessarily one big one.

**Comment by petr-muller** [comment]
@wuhuizuo do you want to do this PR for trigger?

**Comment by wuhuizuo** [comment]
> @wuhuizuo do you want to do this PR for trigger?

Yes

**Comment by wuhuizuo** [comment]
@petr-muller I have contributed a PR, PTAL:
- #323
