### ISSUE TITLE
Retesting flaky PRs is a bug not a feature

### ISSUE THREAD

**Issue by bn222** [kubernetes-sigs/prow#332]
When I submit a pull request to a project with flaky code, I don't want the system to mask the issue by re-running tests. Instead, if a test fails during the job, I expect the process to stop immediately, report an error, and prevent further progress. I believe that flaky behavior should be treated as an error, rather than something that can be recovered from through retries.

To ensure code quality, the system should not attempt to "recover" from failures by re-running tests. Instead, it should report failures as they occur and block the merge of pull requests that exhibit flaky behavior. By doing so, we can ensure that only stable, reliable code is accepted into the project.

**Comment by petr-muller** [comment]
Hello! I can relate to that opinion, but I fail to see the relevancy for Prow project. Prow itself contains no retest functionality.

Some organizations using Prow choose to deploy additional tooling that retests failed jobs, but that is orthogonal to Prow (except that some choose to use e.g. a Prow periodic job to implement it). Kubernetes project uses a [commented](https://github.com/kubernetes/test-infra/tree/master/robots/commenter) that posts `/retest` on PRs with failed jobs. OpenShift has a custom retester component which would be suitable for Prow but would always be an optional component.

So it seems that the appropriate place to voice your concerns would be the team that makes these decisions in whatever org you are concerned with. In kubernetes that would be SIG Testing.

**Comment by BenTheElder** [comment]
In kubernetes/kubernetes we track flaky tests as issues to fix (with a dedicated label and much tooling), but we still want to avoid not merging PRs on unrelated, already tracked test flakes. Subprojects are free to pursue their own approaches though SIG Testing is willing to give guidance.

SIG Testing actually just gave a talk at kubecon on our approach to eliminating flakiness (which is an eternal project, but in MUCH better shape than years ago).

That talk is here:
https://www.youtube.com/watch?v=hl3jjCTTL50

https://kccncna2024.sched.com/event/1hoxc/achieving-and-maintaining-a-healthy-ci-with-zero-test-flakes-antonio-ojea-michelle-shepardson-benjamin-elder-google?iframe=no

If you'd like to discuss changing policies in the broader Kubernetes project, please reach out to [SIG Testing](https://github.com/kubernetes/community/blob/master/sig-testing/README.md) or dev@kubernetes.io, this repo is not the right place to discuss policy, this repo is for implementation of the core CI infrastructure which does not include the retest robot as mentioned above.

/close
