### ISSUE TITLE
Add a search bar to the docs site.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/prow#34]
Is there an easy way to enable a search bar for the documentation site to facilitate navigation?
cc @listx

**Comment by listx** [comment]
Looks like there are many options: https://gohugo.io/tools/search/

**Comment by jihoon-seo** [comment]
Some live examples (FYI: these websites are also using Docsy):
- https://kubernetes.io/docs/home/
- https://glossary.cncf.io/
- ...

**Comment by listx** [comment]
If I run hugo locally I can just edit this line https://github.com/kubernetes-sigs/prow/blob/1005b0be14d394fcb2dca13462951433a79f042a/site/config.toml#L136 to `true` and the sidebar now has a search box. I think this might be sufficient for now. The other option is to create the Google-backed search which is probably better, but then I think we need someone in the community to do the creation of this. @mrbobbytables is [this](https://www.docsy.dev/docs/adding-content/navigation/#setting-up-site-search) something you've done before?

**Comment by cjwagner** [comment]
@listx Fixed this in https://github.com/kubernetes-sigs/prow/pull/38
/close
