### ISSUE TITLE
Migrate existing Prow docs over to this repo

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/prow#4]
Context: https://github.com/kubernetes/test-infra/issues/24821#issuecomment-1057524854 and [this design doc](https://docs.google.com/document/d/17_gyhQipmK_roYqUtwx-hTwi1tn2sd0aG6vdkBn6fKM/edit?usp=sharing)

The existing docs site at https://docs.prow.k8s.io is rather bare-bones and needs more content. Luckily, a lot of content already exists, in the [k/t-i repo](https://github.com/kubernetes/test-infra) (look for Markdown files). We need to identify content that needs to be migrated over, create a migration task list for each of those content areas, and then one-by-one do the actual migration.

Note that any content that is migrated should probably be deleted from k/t-i, so this would require edits to both k/t-i and this repo.

**Comment by listx** [comment]
I've done another refresh of the Legacy Snapshot in https://github.com/kubernetes-sigs/prow/pull/22. After that is merged, we can merge https://github.com/kubernetes/test-infra/pull/27818 to let folks know that the old doc locations in k/t-i are deprecated.

The final step is to update/reorganize/rearrange the contents from the Legacy Snapshot. However we can also just add new content on the side, and later mark things in the Legacy Snapshot as being "dated". The one benefit of the Legacy Snapshot is that at least we get a table-of-contents of every single Prow markdown file, which was previously only discoverable via grepping through the sources (or through enough determined mouse clicks). So in this sense it's something that can happen over a longer period of time. Most likely things will happen organically here.

**Comment by jihoon-seo** [comment]
Hello, I am Jihoon Seo, one of the K8s SIG Docs Korean l10n approvers.

I was organizing my mailbox and noticed the K8s dev group email about "Prow Documentation Revamp", and that mail led me to here.

Here I try suggesting the placement of some Legacy Snapshot documents to the current Prow docs site pages.

[Prow docs site TOC]
- ~[Announcements](https://docs.prow.k8s.io/docs/announcements/)~ (This page seems already having contents.)
- [Overview](https://docs.prow.k8s.io/docs/overview/) ← https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/README.md
  - ~[Architecture](https://docs.prow.k8s.io/docs/overview/architecture/)~ (This page seems already having contents.)
- [Components](https://docs.prow.k8s.io/docs/components/) ← https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/cmd/README.md
  - ~[Deck](https://docs.prow.k8s.io/docs/components/deck/)~ (This page seems already having contents.)
  - ~[Sub](https://docs.prow.k8s.io/docs/components/sub/)~ (This page seems already having contents.)
- ~[GKE Build Clusters](https://docs.prow.k8s.io/docs/build-clusters/)~ (This page seems already having contents.)
- ~[Contribution Guidelines](https://docs.prow.k8s.io/docs/contribution-guidelines/)~ (This page seems already having contents.)
- ~[Metrics](https://docs.prow.k8s.io/docs/metrics/)~ (This page seems already having contents.)

---

Apart from the migrating job of some pages, the first thing I want to do is to update the links in the Legacy Snapshot documents (e.g., https://docs.prow.k8s.io/docs/legacy-snapshot/prow/cmd/readme/).
For now those links are pointing to the pages under https://github.com/kubernetes/test-infra/tree/master/prow/ , where users will just see the DOCUMENTATION DEPRECATION NOTICE.
Updating these ineffective links to point the pages under the Legacy Snapshot documents in the new Prow docs site might give some convenience to the users by enabling to browse over existing documents, although those are deprecated.

**Comment by listx** [comment]
Hello @jihoon-seo, those suggestions sound fine. Ultimately (next quarter? 6 months from now?) the files under the Legacy Snapshot should point to new (replacement) content. I am currently busy prioritizing other things but I hope to get back to this issue by the end of the year.

**Comment by jihoon-seo** [comment]
@listx I revisited https://github.com/kubernetes-sigs/prow/issues/4#issue-1157823837 again, and noticed that I missed your phrase:
> We need to identify content that needs to be migrated over, create a migration task list for each of those content areas, and then one-by-one do the actual migration.

Sorry for opening a huge PR (#26) before creating & suggesting a migration task list.
It would be okay for you (and anyone) to do either:
- give review comments in #26, then I will update the PR, and we can discuss with the updated [Netlify preview](https://deploy-preview-26--k8s-prow.netlify.app/docs/)
- or, we first close #26, create a migration task list, and then one-by-one do the actual migration.

I made a [Google spreadsheet](https://docs.google.com/spreadsheets/d/1vUA34TRLBSkCafZ6pHXvemPeDj7J28z7NST06QsW00M/edit#gid=0) that represents the TOC of my suggestion.
You can also check a [Netlify preview](https://deploy-preview-26--k8s-prow.netlify.app/docs/) of the PR #26.
Please leave any comments, and we would be able to move forward.

**Comment by listx** [comment]
> Sorry for opening a huge PR (https://github.com/kubernetes-sigs/prow/pull/26) before creating & suggesting a migration task list.

Not at all! I'm happy with trying to get #26 merged first, and then iterating (if necessary) after that. I left a few suggestions in that PR, so we can follow up there.

Thank you for taking on this work!

**Comment by listx** [comment]
I think with all the work that @jihoon-seo has done, we can close this issue. We can tackle additional necessary revisions in the umbrella issue in #31.

/close
