### ISSUE TITLE
Document using Tekton Pipelines as prow jobs

### ISSUE THREAD

**Issue by VannTen** [kubernetes-sigs/prow#44]
I understand from kubernetes/test-infra#11888 that prow is able to run tekton pipelines as prow jobs.
However, it does not look like it's documented in docs.prow.k8s.io ("Tekton" search does not return any results)

From the PR conversation, it looks like a follow-up PR was planned, but never materialized (I guess that's the habitual fate of planned documentation :smile: ). 

It looks like tekton has some docs on that ( https://github.com/tektoncd/plumbing/blob/main/docs/prow.md#tekton-pipelines-with-prow ). But as far as I understand, it applies to their prow instance, not in general.

kubernetes/test-infra#13874 seems also relevant, in particular the third comment, but I'm not sure how much has changed since that ?

@Gregory-Pereira you might be interested.

**Comment by qaifshaikh** [comment]
The only major breaking change I see is the deprecation of `PipelineResources` which was used for the clonerefs through `PROW_IMPLICIT_GIT_REF`

**Comment by VannTen** [comment]
You mean in regard to https://github.com/kubernetes/test-infra/issues/13874#issuecomment-521237150 ?

**Comment by qaifshaikh** [comment]
Yeah, I'm not sure how `PROW_IMPLICIT_GIT_REF` works and it is definitely better than having the `git-clone` tekton task as part of the pipeline.
I believe @cjwagner proposed it long time ago

**Comment by qaifshaikh** [comment]
I was able to get the tekton `PipelineRun` working on my setup only because `PipelineResource` is deprecated in `v0.36.0`. It is removed in the next versions on Tekton so it'll probably stop working!

> presubmit.yaml
> 
> ```
> presubmits:
>   {REPO_OWNER}/{REPO}:
>   - name: tekton-test
>     agent: tekton-pipeline # Use the Prow Tekton controller!
>     clone_uri: "git@github.com:{REPO_OWNER}/{REPO}.git"
>     always_run: true
>     skip_report: false
>     rerun_command: /test tekton-test
>     trigger: "(?m)^/test (all|tekton-test),?(\\s+|$)"
>     pipeline_run_spec:
>       serviceAccountName: prow-pipeline
>       pipelineRef:
>         name: hello-goodbye
>       resources:
>       - name: clone
>         resourceRef:
>           name: PROW_IMPLICIT_GIT_REF
> ```

> pipeline.yaml
> ```
> apiVersion: tekton.dev/v1beta1
> kind: Pipeline
> metadata:
>   name: hello-goodbye
> spec:
>   tasks:
>     - name: hello
>       taskRef:
>         name: hello
>       resources:
>         inputs:
>           - name: clone
>             resource: clone
>     - name: goodbye
>       runAfter:
>         - hello
>       taskRef:
>         name: goodbye
>       resources:
>         inputs:
>           - name: clone
>             resource: clone
>   resources:
>     - name: clone
>       type: git
> ```

> task.yaml
> ```
> apiVersion: tekton.dev/v1beta1
> kind: Task
> metadata:
>   name: hello
> spec:
>   resources:
>     inputs:
>       - name: clone
>         type: git
>   steps:
>     - name: echo
>       image: alpine
>       script: |
>         #!/bin/sh
>         echo "Hello World"
> ---
> apiVersion: tekton.dev/v1beta1
> kind: Task
> metadata:
>   name: goodbye
> spec:
>   resources:
>     inputs:
>       - name: clone
>         type: git
>   steps:
>     - name: goodbye
>       image: ubuntu
>       script: |
>         #!/bin/bash
>         echo "Goodbye World!"
> ```

**Comment by qaifshaikh** [comment]
Also found [this](https://github.com/tektoncd/pipeline/issues/1187#issuecomment-1317669922) which makes a lot of sense!
