### ISSUE TITLE
API documentation for ProwJobs

### ISSUE THREAD

**Issue by irbekrm** [kubernetes-sigs/prow#50]
It would be great if the docs site had API docs, especially API reference for `ProwJob`s would be very useful. Something similar to https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/

**Comment by jihoon-seo** [comment]
For anyone's information:
K8s API reference docs are generated using some generators.
These are some related links:

- [Generating Reference Documentation Quickstart Guide](https://kubernetes.io/docs/contribute/generate-ref-docs/quickstart/)
  - [update-imported-docs.py](https://github.com/kubernetes/website/tree/main/update-imported-docs)
- https://github.com/kubernetes-sigs/reference-docs
- `*gen*` files & directory in https://github.com/kubernetes/kubernetes/tree/master/hack
- `*gen*` directories in https://github.com/kubernetes/kubernetes/tree/master/cmd
- ...

**Comment by dobesv** [comment]
The documentation is linked here:

https://docs.prow.k8s.io/docs/jobs/

Click on [PodSpec api reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#podspec-v1-core)

**Comment by dobesv** [comment]
There's a link to the ProwJob source code here: https://docs.prow.k8s.io/docs/life-of-a-prow-job/

Not as nice as the actual doc but it does the job.
