### ISSUE TITLE
Make all existing Prow OWNERS members of the @kubernetes-sigs org.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/prow#68]
The Prow source code and its corresponding OWNERS files are being moved to this repo. The kubernetes/test-infra repo is currently still the source of truth, but we have begun mirroring the source here to prepare.
Code ownership should not change with this source code move, but some of the existing OWNERS file members are not yet members of the @kubernetes-sigs org. We should resolve this, ideally before completing the move, to ensure existing OWNERS have the access they need for this repo.

Example: https://github.com/kubernetes-sigs/prow/pull/67#issuecomment-1806698821
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes-sigs org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * matthyx
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
> * droslean
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
>   * prow/OWNERS
> * smg247
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
>   * prow/spyglass/OWNERS
> * jmguzik
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
> * AlexNPavel
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
>   * prow/bugzilla/OWNERS
>   * prow/jira/OWNERS
>   * prow/plugins/bugzilla/OWNERS

/cc @matthyx @droslean @smg247 @jmguzik @AlexNPavel
/assign @timwangmusic

**Comment by matthyx** [comment]
Thanks @cjwagner !
Maybe we could also discuss how could I become a prow APPROVER, because after talking to @BenTheElder in Chicago, it looks like you're missing some manpower recently.

**Comment by stevekuznetsov** [comment]
Should be as easy as getting the nomination like normal!
