### ISSUE TITLE
Forking Prow

### ISSUE THREAD

**Issue by timwangmusic** [kubernetes-sigs/prow#77]
We are moving the `/prow` directory from [k8s.io/test-infra](https://github.com/kubernetes/test-infra) repo to this repo.

The migration should satisfy the following requirements:
- Developers use a dedicated Prow repository on GitHub.
- The Prow repository must not depend on libraries in the test-infra repo.
- Prow commit history is retained in the new repository.
- Presubmit and postsubmit Prow jobs such as image publishing will run on the new repository.

**Comment by upodroid** [comment]
Is it possible to copy the contents of the prow folder inside k/test-infra to the root of this repo?

**Comment by upodroid** [comment]
This work is done now. The code was moved to this repo.

I have an open PR to get rid of prow/prow in the import path and move prow/cmd and prow/pkg to the root of the repo.

https://github.com/kubernetes-sigs/prow/pull/101
